apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: supply-chain-security
spec:
  steps:
  - name: download-syft
    image: alpine:3.16
    resources: {}
    script: |
      #!/bin/sh
      apk add --no-cache curl unzip
      curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | \
      sh -s -- -b /workspace/source/bin v0.52.0
      chmod +x /workspace/source/bin/syft
      echo "export PATH=$PATH:/go/bin:/usr/local/go/bin:/workspace/source/bin" >> .jx/variables.sh
  - name: build-and-push-sbom
    image:  ghcr.io/oras-project/oras:v0.13.0
    env:
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          key:  password
          name: tekton-git
    - name: GIT_USER
      valueFrom:
        secretKeyRef:
          key:  username
          name: tekton-git
    resources: {}
    script: |
      #!/bin/bash
      source .jx/variables.sh
      syft /workspace/source/image.tar --scope all-layers -o spdx-json > /workspace/source/sbom.json
      echo $GIT_TOKEN | oras push -u $GIT_USER --password-stdin ghcr.io/$DOCKER_REGISTRY_ORG/$REPO_NAME:$VERSION-sbom /workspace/source/sbom.json
      echo $GIT_TOKEN | oras push -u $GIT_USER --password-stdin ghcr.io/$DOCKER_REGISTRY_ORG/$REPO_NAME:latest-sbom /workspace/source/sbom.json

