apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/60bed6408732c1eda91a15713f51a9f97dcb1757/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-release-version:1.0.42
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env bash
            VERSION=$(jx-release-version)
            echo $VERSION > VERSION

        - image: gcr.io/jenkinsxio/jx-boot:3.1.99
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: build-basic-auth-username
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step credential -s jenkins-x-chartmuseum -k BASIC_AUTH_USER -f /builder/home/basic-auth-user.json
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: build-basic-auth-password
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step credential -s jenkins-x-chartmuseum -k BASIC_AUTH_PASS -f /builder/home/basic-auth-pass.json
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: build-release
          resources: {}
          script: |
            #!/bin/sh
            make release

  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
