apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/005e78cf69b643862344397a635736a51dd1bd89/tasks/git-clone/git-clone.yaml
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources: {}
          volumeMounts:
          - mountPath: /home/jenkins
            name: workspace-volume
          - mountPath: /etc/podinfo
            name: podinfo
            readOnly: true
          workingDir: /workspace/source
        steps:
        - command:
          - jx step next-version --use-git-tag-only --tag
          image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: next-version
          resources: {}
        - image: gcr.io/jenkinsxio/jx-cli:latest
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx gitops variables
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: build-basic-auth-username
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step credential -s jenkins-x-chartmuseum -k BASIC_AUTH_USER -f /builder/home/basic-auth-user.json
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: build-basic-auth-password
          resources: {}
          script: |
            #!/usr/bin/env bash
            jx step credential -s jenkins-x-chartmuseum -k BASIC_AUTH_PASS -f /builder/home/basic-auth-pass.json
        - image: gcr.io/jenkinsxio/builder-go:2.1.142-761
          name: build-release
          resources: {}
          script: |
            #!/bin/sh
            make release
        volumes:
        - downwardAPI:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
          name: podinfo
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
