apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.1.293
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: gcr.io/jenkinsxio/builder-machine-learning:2.1.150-769
          name: build-flake8
          resources: {}
          script: |
            #!/bin/sh
            source /root/.bashrc
            flake8
        - image: gcr.io/jenkinsxio/builder-machine-learning:2.1.150-769
          name: build-testing
          resources: {}
          script: |
            #!/bin/sh
            source /root/.bashrc
            pytest
        - image: gcr.io/jenkinsxio/builder-machine-learning:2.1.150-769
          name: build-training
          resources: {}
          script: |
            #!/bin/sh
            source /root/.bashrc
            python3 -m pip install -r ./requirements.txt
            python3 app.py
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
