apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: lint
spec:
  pipelineSpec:
    workspaces:
    - name: output
    tasks:
    - name: from-build-pack
      workspaces:
      - name: output
        workspace: output
      resources: {}
      taskSpec:
        workspaces:
        - name: output
          mountPath: /workspace
        metadata: {}
        stepTemplate:
          env:
          - name: NPM_CONFIG_USERCONFIG
            value: /tekton/home/npm/.npmrc
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            limits: {}
          workingDir: $(workspaces.output.path)/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.11.98
          name: jx-variables
          resources:
            # set requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
          script: |
            #!/usr/bin/env sh
            jx gitops variables
            jx gitops pr variables
        - image: node:20-slim
          name: build-lookml-lint
          resources: {}
          script: |
            #!/bin/sh
            npm install -g @looker/look-at-me-sideways --allow-root --unsafe-perm=true
            lams --reporting=no \
              --allow-custom-rules \
              --jenkins
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
