apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: NPM_CONFIG_USERCONFIG
            value: /tekton/home/npm/.npmrc
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          volumeMounts:
          - mountPath: /tekton/home/npm
            name: npmrc
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-release-version:2.2.6
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx-release-version > VERSION
        - image: ghcr.io/jenkins-x/jx-boot:3.1.353
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: mobiledevops/flutter-sdk-image:2.0.1
          name: build
          resources: {}
          script: |
            #!/usr/bin/bash
            flutter pub get
            flutter test
            flutter build apk
        - image: gcr.io/jenkinsxio/jx-changelog:0.0.36
          name: promote-changelog
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            echo "TODO: replace version strings in source code"

            git add * || true
            git commit -a -m "chore: release $VERSION" --allow-empty
            git tag -fa v$VERSION -m "Release version $VERSION"
            git push --force origin v$VERSION

            jx changelog create --version v${VERSION}
        - command:
          - jx-updatebot
          - pr
          image: gcr.io/jenkinsxio/jx-updatebot:0.0.57
          name: promote-release
          resources: {}
        volumes:
        - name: npmrc
          secret:
            optional: true
            secretName: npmrc
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
